name: Elixir CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.10.3
        otp-version: 22.1

    - uses: actions/cache@v1
      id: deps-cache
      with:
        path: deps
        key: ${{ runner.os }}-mix-cache-${{ hashFiles('mix.lock') }}-v1

    - uses: actions/cache@v1
      id: build-cache
      with:
        path: _build
        key: ${{ runner.os }}-build-cache-${{ hashFiles('mix.lock') }}-v1

    - uses: actions/cache@v1
      id: dialyzer-plt
      with:
        path: priv/plts
        key: ${{ runner.os }}-plts-cache-${{ hashFiles('mix.lock') }}-v1

    - name: Install Dependencies
      run: mix deps.get

    - name: Check Formatting
      run: mix format --check-formatted

    - name: Check Types
      run: mix dialyzer

    - name: Run Tests
      run: mix test
